const provpass2 = {
    id: 2,
    title: "Provpass 2 (Verbal)",
    totalTimeInMinutes: 55,
    texts: {
        "las1": {
            title: "Medborgarkompetens",
            content: `I den offentliga debatten finns en tydlig förväntan på skolan att fungera som en arena för att utveckla unga människor till goda medborgare. När svensk utbildningspolitik har formulerats har medborgarperspektivet traditionellt haft en framträdande roll. Det finns emellertid ett avvägningsproblem mellan skolans medborgarfostrande, demokratiska uppdrag och uppdraget att förbereda elever för yrkeslivet.

Traditionellt har SO-undervisningen haft ett stort ansvar för skolans demokratiska uppdrag, för att lära eleverna hur man deltar och agerar som medborgare i ett demokratiskt samhälle. Bland SO-ämnena är det framför allt i ämnet samhällskunskap som man brukar ta upp och diskutera de demokratiska värdena och utveckla elevernas förmåga att granska, värdera och ta ställning i samhällsfrågor och internationella utvecklingsfrågor.

Reformen av gymnasieskolan (Gy 11) innebar en förändring så till vida att mindre fokus numera läggs på skolans medborgarfostrande uppdrag medan ett tydligare fokus läggs på att förbereda eleverna antingen för yrkeslivet och fortsatt yrkesutbildning eller för fortsatta studier. Detta kommer bland annat till uttryck i att ämnet samhällskunskap på gymnasieskolans yrkesprogram halverats från 100 till 50 poäng.

Det övergripande syftet med vårt forskningsprojekt är att undersöka om reformen av gymnasieskolan påverkar yrkesprogramelevernas medborgarkompetens, det vill säga deras demokratiska värderingar, tillit till egna färdigheter och kommunikativa förmågor samt politiska kunskaper och politiska engagemang.

I projektet fokuserar vi på två aspekter av samhällskunskapsundervisning. För det första undersöker vi effekter av undervisningsmängden (antalet undervisningstimmar). Här knyter vi an till en internationell diskussion om effekter av utbildning. Utbildningsreformen innebar dock inte enbart en minskning av antalet timmar utan också en viss förändring av formen för undervisningen i riktning mot mer traditionell katederundervisning. För det andra riktar vi därför in oss på typen av undervisning. Vi genomför ett empiriskt test där vi undersöker vilka effekter på medborgarkompetens så kallad deliberativ undervisning har jämfört med traditionell katederundervisning.

Joakim Ekman, Pär Zetterberg, Mikael Persson & Klas Andersson

*deliberativ undervisning = undervisning som bygger på samtal*`
        },
        "las2": {
            title: "Två inlägg i debatten om ljudboken",
            content: `**INLÄGG 1**
I den senaste debatten om ljudböcker har det som vanligt handlat om pengar, branschen och de nya formaten. Den gamla floskeln att ljudboken vidgar det litterära formatet brukar följas av en ömsint men nedlåtande kommentar om boken som ålderdomlig, som om man vill hänga med i utvecklingen även när den leder mot botten.

Mer sällan talar man om att det inte är samma sak att lyssna som att läsa. Vissa kritiker verkar inte ens reflektera över skillnaden, som exempelvis Expressens litteraturkritiker Jens Liljestrand som, utan att blygas, i en text om Lydia Sandgrens Samlade verk tillstår att han faktiskt inte har läst boken utan bara lyssnat till den: ”Själv slukade jag den under veckor av ensamma barnvagnspromenader med Ludvig Josephsons varma röst i hörlurarna, genom trivsamma 28 timmar och 35 minuter.” När till och med en känd kritiker som Liljestrand inte förstår att det är en väsentlig skillnad mellan att läsa och att lyssna så blir det ju svårt att övertyga oss andra om det tryckta ordets överlägsenhet jämfört med det inspelade ljudet när det kommer till litteratur.

Läsning av en bok kräver ett pågående arbete som ljudböcker inte kräver. I boken finns nämligen ingen gravitation. Man kan inte läsa en bok och diska samtidigt, eller läsa en bok och surfa på nätet samtidigt. När du vänder tillbaka blicken efter att ha tittat på något annat så är du kvar på samma sida i boken, som inte rör sig framåt av sig själv. Ljudboken har gått vidare, men boken går bara vidare genom din läsning. Det är det som gör boken svårare och det kanske också är det som ligger bakom litteraturens särställning.

Det ljudboken gör är att tala till människans urgamla vilja att få något utan att betala för det. Det är samma vilja som ligger bakom drömmarna om evighetsmaskiner, att kunna göra guld av gråsten eller vin av vatten – eller, som i fallet med ljudboken, att läsa utan att läsa. Jag har inget principiellt emot ljudboksformatet, bara man inte kallar det läsning, för det är det inte.

Provocerande nog kommer sådana utsagor ofta från människor som arbetar med litteratur, och alltså borde kunna skilja på läsning och lyssning, och dessutom borde förstå att lyssningen aldrig kan ersätta den rikedom som läsandet av en bok ger. I Expressen skriver exempelvis Jakob Nilsson: ”Bland ljudbokslyssnarna finns såväl de som annars inte alls hittat fram till litteraturen som de som tidigare konsumerat i huvudsak deckare, bara bytt format.”

Problemet är att det inte fungerar så. Man råder inte bot på oförmågan att läsa litteratur genom att ta bort läsandet, lika lite som man råder bot på okunskap genom att ta bort det som kallas lärandets smärta, nämligen den förvandling av människan som sker i läsningen och i lärandet, men som är mödosam – därav smärtan – precis som all förändring. Dit kommer man inte när man kör bil, diskar eller försöker somna, utan det kräver fokus och ansträngning.

En annan sak man inte talar om är att digitaliseringen är en del av en helt ny marknadsekonomi som härstammar från Silicon Valley och som handlar om att teknikföretagen vill få så många människor på planeten som möjligt att streama och vara online för att dela med sig av information om sig själva, som i sin tur bearbetas för att skapa så kallade prediktionsprodukter som samma företag sedan säljer vidare till reklambyråerna så att de kan göra riktade annonser med så hög precision som möjligt. Med tanke på denna nya marknadslogik kan man faktiskt fråga sig om ljudboksföretaget Storytels affärsidé ens handlar om ljudböcker. Den gjorde säkert det från början, men numera handlar Storytels affärsidé sannolikt snarare om att få ut så mycket information som möjligt från sina kunder för att sedan tjäna nya pengar med hjälp av dessa data.

För att detta ska bli så lönsamt som möjligt måste man ha många kanaler öppna mot användarna i form av streamingtjänster och enheter som samlar information. Man kan läsa om det i företagets integritetspolicy som finns på deras hemsida eftersom lagen kräver det, men som ändå ingen läser. Storytel hymlar inte heller med att man också vill komma åt allt innehåll från sina användares Facebook-konton. I sitt policydokument skriver man att man kommer ”att samla in och behandla sådana personuppgifter som du har givit Facebook”. Men som sagt, detta talar man aldrig om när man talar om ljudboken. Om debatten inte handlar om läsning, vilket den borde, så skulle den åtminstone kunna handla om detta.
*Ola Nilsson*

**INLÄGG 2**
Författaren Ola Nilssons text i Aftonbladet i helgen blev en vattendelare. En högljudd debatt fördes snart i en mängd kommentarsfält, och sällan har det varit så tydligt hur diametralt olika människor ser på det växande ljudboksformatet och vad det betyder för litteraturen. Jag har vänner som i princip fastslog att den var det mest sanna som skrivits om litteraturens erbarmliga tillstånd på flera år, medan andra ansåg texten bestå enbart av billigt effektsökeri. Värt att notera – båda extremerna uttrycktes av människor som är professionellt verksamma i bokbranschen.

Ola Nilssons påpekande att läsning till skillnad från lyssning kräver att man på egen hand för texten framåt är visserligen korrekt, men gör det verkligen att det blir svårare att läsa än att lyssna? Kan det inte lika gärna vara tvärtom? Att hänga med i ett skeende i en lyssnad text som någon annan styr över – är inte det svårare än att med sina egna ögon bestämma över tempo och pauser i sin läsning? Borde det inte vara en lika svår konst att bli en god lyssnare som en god läsare?

Missförstå mig inte – läsning är livsviktigt, och jag tillhör inte dem som tycker att lyssning och läsning alltid går att likställa och skulle aldrig säga att jag läst en ljudbok (däremot lyssnar jag på ljudböcker dagligen). Men samtidigt – är sysslorna verkligen så väsensskilda som många vill göra gällande?

Inte för hjärnan, vad det verkar. En ofta citerad forskare är amerikanen Daniel T Willingham, som studerat kognitiva processer vid läsning och lyssning. I en text i New York Times från 2018 beskriver han sysslorna som i stort sett identiska när hjärnan hanterar dem. Men i samma artikel citerar han även en empirisk jämförelsestudie där vissa studenter fick lyssna på en text och andra läsa den. När det sedan blev tentadags visade det sig att de som läst texten kom ihåg betydligt mer.

Men ... då är väl läsning trots allt bättre? Kanske, men inte nödvändigtvis. Skillnaden i prestation skulle också kunna bottna i att vi skolas betydligt mer i att lära oss läsa och tolka skriven text än vi lär oss att på allvar lyssna på och minnas det vi hör – studenterna saknade helt enkelt de rätta verktygen för att bäst komma ihåg och förstå vad de lyssnade på.

Ja, nu spekulerar jag mest, men det tycker jag nog att Ola Nilsson gjorde i sin artikel också.
*Daniel Åberg*`
        },
        "las3": {
            title: "Fiskodling vid vattenkraftverk",
            content: `Data från miljöövervakning av svenska inlandsvatten visar att vi de senaste 30 åren har haft en kraftig nedgång av halten närsalter (främst fosfor och kväve). Denna oligotrofiering kan vara positiv i odlingslandskapet och urbana områden, där vi sedan nära 100 år har byggt upp ett stort näringsöverskott. För vatten som avvattnar skog och fjäll, det vill säga majoriteten av våra norrländska älvar, är situationen däremot kritisk. Här ser vi idag att näringshalterna bara fortsätter att minska och nu har nått kritiskt låga nivåer även i de vattendrag som är minst påverkade av människan, med den oreglerade Vindelälven som ett påtagligt exempel. Den förhärskande teorin idag är att denna generella nedgång i näringshalter kan knytas till ett ökat näringsbehov i våra skogar påskyndat av ett varmare klimat och till minskad erosion då allt mer av kalfjället täcks av växter.

En annan möjlig faktor, som gör situationen än mer allvarlig, har att göra med de naturligt höga halter av aluminium och ökande mängder av järn som förekommer i våra norrländska vatten. Om det inte finns tillgängligt organiskt material i litoralen (strandzonen) som fosfor kan bindas in i, så kommer fosforn att reagera med detta aluminium och järn ute i pelagialen (den fria vattenmassan) och bli biologiskt otillgänglig. I en första pilotstudie i Ströms Vattudals vattenmagasin fann vi att bara en mindre del av fosforn i sedimentet är tillgänglig för biologisk produktion av just den anledningen. Detta var oberoende av om mätningen gjordes uppströms, nedströms eller direkt under den fiskodling som finns där, med den skillnaden att den totala mängden fosfor var större i sedimentprover tagna direkt under fiskodlingen. Denna pilotstudie indikerar att fosfor i sedimentet i dessa miljöer är betydligt hårdare bunden i aluminium och järn än den är i sediment under och nära fiskodlingar i Bottenhavet eller själva Östersjön.

Hur den sedimentbundna fosforns tillgänglighet kan ändras över tid och med ändringar i miljön i dessa vatten är nu föremål för mer detaljerade studier av forskare vid Sveriges lantbruksuniversitet (SLU). Studierna syftar till att öka förståelsen av de underliggande mekanismerna bakom fosforns omsättning och kretslopp i dessa vatten, liksom av hur en ändrad tillförsel av biologiskt tillgänglig fosfor påverkar fosforns kretslopp och därmed också systemets förutsättningar för biologisk produktion.

Från långtidsstudier vet vi att närsalterna lakas ut ur kraftverkens vattenmagasin efter en reglering och att de når en topp i pelagialen de första femton åren. Sedan sjunker näringshalterna och stabiliseras på en onaturligt oligotrof nivå, vilket beror på att upprepad och oregelbunden torrläggning av stränderna skadar eller helt slår ut litoralens vegetation och näringsväv. I en naturlig sjö utgör denna zon en viktig och mycket produktiv del av ekosystemet. I den produktiva litorala zonen fångas näring in av strandvegetationens bottenlevande alger som i sin tur utgör en födobas för bakterier och andra nedbrytare samt för bottenlevande insekter och kräftdjur som är en viktig födoresurs för många fiskarter.

Vattenregleringen har med andra ord stöpt om födoväven från litoral till pelagial dominans, vilket annars bara brukar gälla för öppna hav eller mycket stora sjöar med liten landkontakt. Denna förändring i kombination med den generellt sjunkande halten av näringsämnen i alla våra inlandsvatten leder till att vi får en extrem näringsbrist i våra kraftverksdammar med minskad biologisk produktivitet och mångfald som följd. Detta begränsar i sin tur fiskens födotillgång och skapar populationer av tusenbröder, det vill säga små och långsamväxande individer.

Ett undantag från sådana ekosystemeffekter i dessa onaturligt oligotrofa vatten tycks nu skönjas i magasin som länge har haft öppen fiskodling, med andra ord vatten där det kontinuerligt och under lång tid har tillförts organiskt tillgänglig näring. Detta stämmer väl överens med såväl svenska som nordamerikanska studier där man tillfört konstgödning till kraftverksdammar och fått en signifikant och positiv ökning av den biologiska produktionen. En central målsättning är därför att utvärdera om biologiskt tillgänglig näring från fiskodling kan öka ekosystemets produktivitet och därmed tillväxten hos de vilda fiskbestånden, kopplat till en ökning av pelagiska mikroalger och bakterier. Det skulle i så fall kunna utgöra ett alternativ till den föda som i en naturlig sjö kommer från litoralen, vilken i reglerade kraftverksdammar är permanent utslagen.

Med andra ord skulle fiskodlingen kunna utföra en miljötjänst. Detta är speciellt intressant då ny forskning visar att fiskarnas gödsel utöver näringsämnen innehåller biologiskt aktiva metaboliter som producerats av deras tarmbakterier. Metaboliterna har en direkt påverkan på växters genetiska uttryck, stimulerar tillväxten och kan dessutom fungera som ”probiotika” för växterna. Detta tycks även gälla för mikroalger som utgör basen i den pelagiska födokedjan som vi ser dominera system med förstörd litoral. Det kanske inte är en slump att människan i många tusen år har kombinerat fisk- och växtodling, där kombinationen fisk- och risodling i Sydostasien kanske är det äldsta och mest välkända exemplet.

Dagens kraftverksdammar är alla äldre och släpper inte längre ut betydande mängder näring nedströms, utan suger tvärtom girigt i sig den lilla mängd näring som finns för biologisk produktion. Historiskt återförde dåtidens stora populationer av vandringsfisk näring från havet till inlandet, men minskade vildpopulationer och kraftverksdammarnas vandringshinder begränsar i dagsläget detta.

Fiskodling baserad på kretsloppsbaserade foderråvaror som till del hämtas från Östersjön och dess avrinningsområde skulle till viss del kunna återställa en sådan historisk näringstransport. Lars Ove Eriksson, tidigare professor i Akvakultur vid SLU, kallade detta för ”Robin Hood-effekten”, det vill säga att ta från de rika och ge till de fattiga. På senare tid har forskare vid SLU genomfört en rad större projekt, dels tillsammans med våra grannländer runt Östersjön, dels i nationella projekt som 5 ton grön fisk i disk (5TFiD). Dessa projekt har visat att det är fullt möjligt, både ekonomiskt och praktiskt, att ta fram ett konkurrenskraftigt fiskfoder av hög kvalitet från lokala foderråvaror, där varje kilo foder minskar näringsbelastningen i Östersjön.

Anders Kiessling och Martyn Futter`
        },
        "elf1": {
            title: "Comics in Science",
            content: `There are many aspects of comics that make them a promising tool for science communication. Comics can combine engaging storytelling with the structure of diagrams, they allow us to travel into distant worlds with fictional characters, and they map abstract concepts onto more familiar ones with metaphors. A more fundamental question, however, remains to be answered: Do comics actually improve learning or engagement with science?
            
Some research results are encouraging and suggest that the true value of comics may be engaging those readers who are less likely to seek other forms of science communication. Yet, although they may be easy to read, making good comics takes as much time and skill as making a good documentary. At the end of the day, the communication of science in comics will be only as good as the comics themselves.`
        },
        "elf2": {
            title: "Impressions",
            content: `Research by Christopher Olivola and Alexander Todorov suggests that rapid judgments about the personality traits of political candidates, based solely on their appearance, can predict their electoral success. In other words, voters rely heavily on appearances when choosing which candidate to elect. Since voters need to navigate their way through the flood of information available about candidates in order to make fully informed choices, it is no surprise that they take mental shortcuts to get to their final decision. Olivola and Todorov conclude: “Getting people to overcome the influence of first impressions will not be an easy task. The speed, automaticity, and implicit nature of appearance-based trait inferences make them particularly hard to correct. Moreover, often people don’t even recognize that they are forming judgments about others from their appearances.”`
        },
        "elf3": {
            title: "Indie Bookstores",
            content: `For years, bookstores have been the repository of, along with books, a lot of highly romantic feelings. They crop up in fictional settings rather more often than their retail peers; the list of examples is long and charming, and includes the Shop Around the Corner (You’ve Got Mail), the Travel Book Co. (Notting Hill) and Women and Women First (Portlandia). Part of that appeal lies in the sense that bookstores, especially independent ones, belong to a bygone era – there’s a delicious moribund melancholy about them. Last chance to see.

Ironically, that reputation may have contributed to an unexpected plot twist – independent bookstores are actually really healthy. In May of 2016, the American Booksellers Association informed a grieving public that the year before, the number of its member stores had actually increased, from 1,712 to 1,775. Counting multiple locations, the total climbed to 2,311. You can’t even call it a fluke because that was the seventh straight year it happened.

The numbers are growing because business is growing. Independent-bookstore sales were up around 5% in the first four months of 2016. Indies accounted for about 10% of all books sold in 2015, up from 7% the year before. This isn’t a reflection of good news across the broader book business: the number of Barnes & Nobles stores has shrunk from 726 in 2009 to 640 in 2016, and sales at the chain have slipped every year since 2012. It’s also not true in the U.K., where the number of independent bookstores (sorry, bookshops) shrank 3% in 2015. But apparently Americans like indie bookstores, and they like buying things there.

The revival of the neighborhood bookstore has a few different causes. Some are prosaic: new technology makes things like accounting and inventory management easier for small stores. The growth of social media makes it easier to promote events. The demise of the Borders chain in 2011 had the effect, in some markets, of taking competitive pressure off indies.

But there are other, less tangible reasons, too. When Brian Lampkin followed his wife’s medical practice to Greensboro, N.C., he felt the lack of an indie bookstore downtown. “I just have this prejudice,” he says, “that every city needs a really good independent bookstore.” So he did something about it: he renovated a beautiful old brick building dating from 1898, and in 2013 he opened Scuppernong Books there; the bookstore is paired with a wine-and-coffee café in the same space. Scuppernong stocks a literary-leaning list. “We’re letting Amazon and Barnes & Noble take care of the best sellers,” Lampkin says. “Where are you going to get poetry? Some Barnes & Nobles you walk into, you’re lucky to find Emily Dickinson.” The store now has a staff of eight.

Businesses like Scuppernong are also benefiting from a surprise twist in the story of the e-book. After Amazon launched the Kindle in 2007, e-books began a relentless conquest of the book market, from 9% of unit sales in 2010 to 28% in 2013, at which point their eventual dominance began to feel like technological manifest destiny. But the paper book – a piece of information technology that has, after all, been tested and honed over the past 2,000 years – has declined to give way that easily. In 2015, the share of e-books (at least the non-self-published kind) actually receded to 24%. The book market appears to have rebalanced itself into a complex mix of paper and digital, with neither format completely dominating, and plenty of room for brick-and-mortar retailers.

It’s becoming apparent that just as paper books turned out to have advantages over e-books, reality has its good points when compared with its virtual, two-dimensional shadow. Book-industry analysts talk a lot about “discovery,” by which they mean the way people find and purchase new books. It turns out, according to consumer research, that the best method for book discovery is still standing in a roomful of books and browsing – ahead even of click-tracking, data-mining if-you-liked-thisyou’ll-like-that algorithms.

No question, indie bookstores face challenges. Theirs is not a huge growth business. No one’s getting rich. “The most surprising thing is how many times people just say thank you,” Brian Lampkin says. “I think they sort of get that there’s no real reason to do this other than love and commitment.”

Even as indies gain ground, online retailers are booming, too: their share of the book market was up 5% in 2015. Amazon opened a brick-and-mortar bookstore in Seattle the same year, announcing a second one, in San Diego.
*Lev Grossman, Time*`
        },
        "elf4": {
            title: "Food for Thought",
            content: `As a dish is handed down the generations, passed between cultures, or shipped abroad, its recipe is reinscribed by all those who eat it. At first, the differences might seem small, but over time it can change out of all recognition. New ingredients are substituted for old, new methods of preparation are adopted and, every now and then, new names are bestowed. But while the accretion of such alterations may obscure the original, each new ‘layer’ tells us something about a different group of consumers: their tastes, their economy, their language and their relationship with those from whom they adopted the dish. This is particularly true of Anglo-Indian cuisine, where, of course, the most obvious examples are curry and mulligatawny soup.`
        },
        "elf5": {
            title: "Breaking Up",
            content: `Few animals appear more affectionate than the black-browed albatross. These large seabirds, whose dark eyebrows shadow their eyes like mascara, are socially monogamous and often mate for life. Their romantic-seeming “marriages” have a practical purpose: staying with the same partner builds trust, which is essential as the pair alternates between lengthy foraging trips and egg-incubation duties. But “divorce” is not unheard of. As is the case with other monogamous animals, a female albatross will leave a partnership that lacks breeding success. The process is relatively understated and free from noisy squabbles, says University of Lisbon biologist Francesco Ventura. Often when a female deems the partnership unsuccessful over the course of a year, she will simply appear with a different male in the following breeding season.`
        },
        "elf6": {
            title: "18th Century Criminals",
            content: `People in 18th century Britain used the term ‘criminal’ in much the same way we do today: someone who committed a crime and was taken to court was a ‘criminal’ and was referred to as such. It didn’t matter if they were a starving waif stealing an apple from a grocer’s stall for the first time; the branding didn’t distinguish them from a highwayman, murderer or career house breaker. This wasn’t just a semantic quirk, it was generally held that anyone who would stoop to commit a crime was already morally bankrupt and was starting a spiral down into a life of villainy, if they weren’t already there.`
        }
    },
    questions: [
        { id: 1, text: "1. prognos", options: ["A besked", "B utvärdering", "C sammanfattning", "D förutsägelse", "E redovisning"], correctAnswer: "D", category: "ORD" },
        { id: 2, text: "2. slug", options: ["A ivrig", "B otäck", "C girig", "D envis", "E listig"], correctAnswer: "E", category: "ORD" },
        { id: 3, text: "3. eftertrakta", options: ["A ta reda på", "B följa efter", "C härma", "D vilja ha", "E fundera på"], correctAnswer: "D", category: "ORD" },
        { id: 4, text: "4. potential", options: ["A stor skicklighet", "B inneboende möjligheter", "C sannolikt resultat", "D betydande framgångar", "E starka förhoppningar"], correctAnswer: "B", category: "ORD" },
        { id: 5, text: "5. utomordentlig", options: ["A märklig", "B förhastad", "C oavsiktlig", "D förträfflig", "E noggrann"], correctAnswer: "D", category: "ORD" },
        { id: 6, text: "6. plombering", options: ["A avskärmning", "B omledning", "C försegling", "D urgröpning", "E återställning"], correctAnswer: "C", category: "ORD" },
        { id: 7, text: "7. miserabel", options: ["A eländig", "B vilsen", "C bitter", "D plågsam", "E otrevlig"], correctAnswer: "A", category: "ORD" },
        { id: 8, text: "8. fadäs", options: ["A elakt skämt", "B kort vistelse", "C påminnelse", "D oförutsedd utgift", "E pinsamt misstag"], correctAnswer: "E", category: "ORD" },
        { id: 9, text: "9. ingalunda", options: ["A inte alls", "B i onödan", "C undantagsvis", "D otillräckligt", "E ingenstans"], correctAnswer: "A", category: "ORD" },
        { id: 10, text: "10. erinra sig", options: ["A undersöka", "B minnas", "C lugna sig", "D avvakta", "E invänta"], correctAnswer: "B", category: "ORD" },
        { id: 11, text: "11. Vilket är det huvudsakliga målet med den studie som presenteras i texten?", options: ["A Att ta reda på vilken betydelse undervisningsformen har för ämnet samhällskunskap.", "B Att ta reda på hur väl ämnet samhällskunskap lämpar sig för utbildning i så kallad medborgarkompetens.", "C Att ta reda på hur mycket elevers engagemang påverkar deras kunskaper i samhällsfrågor.", "D Att ta reda på om förändringen av gymnasieskolan påverkar elevers samhällsengagemang."], correctAnswer: "D", category: "LÄS", textRef: "las1" },
        { id: 12, text: "12. Vad tycks ha stått i fokus vid utformningen av den skolreform som texten tar upp?", options: ["A Elevernas framtida arbetsliv.", "B En stärkt demokrati.", "C Kunskaperna i teoretiska ämnen.", "D Skolans fostrande uppdrag."], correctAnswer: "A", category: "LÄS", textRef: "las1" },
        { id: 13, text: "13. Vilket påstående sammanfattar bäst vad Ola Nilsson signalerar med sin text?", options: ["A Ljudboksmarknaden behöver regleras.", "B Ljudboksförlagen satsar inte på kvalitetslitteratur.", "C Det är bättre att läsa böcker än att lyssna på dem.", "D Det är meningslöst att debattera ljudboken."], correctAnswer: "C", category: "LÄS", textRef: "las2" },
        { id: 14, text: "14. Ola Nilsson menar att den tryckta boken saknar ”gravitation”. Hur kan man bäst sammanfatta Daniel Åbergs svar på detta?", options: ["A Ljudboken aktiverar andra sinnen vilket underlättar inlärningen.", "B Att lyssna på en bok kräver också en arbetsinsats, inte helt olik den att läsa.", "C Det viktiga är litteraturens innehåll, inte hur det presenteras.", "D Att lyssna och att läsa är helt olika aktiviteter som inte kan jämföras."], correctAnswer: "B", category: "LÄS", textRef: "las2" },
        { id: 15, text: "15. Vad vill Daniel Åberg få sagt angående resultatet i den empiriska jämförelsestudie som han refererar till?", options: ["A Att resultatet kan vara en följd av läsningens höga status i skolan.", "B Att resultatet visar på studenters skilda förutsättningar.", "C Att resultatet tyder på att läsning och lyssning är likartade processer.", "D Att resultatet bevisar att läsning är den bästa inlärningsmetoden."], correctAnswer: "A", category: "LÄS", textRef: "las2" },
        { id: 16, text: "16. Vilken funktion fyller den sista meningen i Daniel Åbergs text?", options: ["A Den sammanfattar hans resonemang.", "B Den nyanserar hans i övrigt ensidiga argumentation.", "C Den synliggör att han och Ola Nilsson egentligen är ganska överens.", "D Den skapar en viss distans till diskussionen som helhet."], correctAnswer: "D", category: "LÄS", textRef: "las2" },
        { id: 17, text: "17. Vad anges i texten som en orsak till att näringshalterna i Vindelälven och andra norrländska inlandsvatten har förändrats?", options: ["A En ökad mängd näring har tagits upp av skogens växtlighet.", "B Anlagda kraftverksdammar har ökat mängden järn och aluminium i vattendragen.", "C Fiskodlingar har krävt allt större mängder näring.", "D Ett varmare klimat har ökat strandvegetationens utbredning."], correctAnswer: "A", category: "LÄS", textRef: "las3" },
        { id: 18, text: "18. Vad är enligt texten orsaken till att mycket av fosforn i Ströms Vattudal inte är tillgänglig för biologisk produktion?", options: ["A Avsaknaden av vegetation i litoralen.", "B Den ökande halten aluminium i pelagialen.", "C Att fosforn är bunden i organiskt material.", "D Att fosforn har koncentrerats till bottenmiljön vid fiskodlingen."], correctAnswer: "A", category: "LÄS", textRef: "las3" },
        { id: 19, text: "19. Hur beskriver man bäst, utifrån texten, relationen mellan vattenreglering och fiskodling om man ser till näringsinnehållet i en kraftverksdamm?", options: ["A Vattenregleringen kan förvärra fiskodlingens negativa effekter.", "B Vattenregleringen kan påskynda fiskodlingens positiva effekter.", "C Fiskodlingen kan motverka vattenregleringens positiva effekter.", "D Fiskodlingen kan kompensera för vattenregleringens negativa effekter."], correctAnswer: "D", category: "LÄS", textRef: "las3" },
        { id: 20, text: "20. Vilken frågeställning står i centrum för texten?", options: ["A Hur minskar vi Östersjöns näringsöverskott?", "B Hur kan svenska inlandsvatten bli mer näringsrika?", "C Hur utvecklas vilda fiskbestånd i näringsfattigt vatten?", "D Hur kan näringen i svenska inlandsvatten utnyttjas bäst?"], correctAnswer: "B", category: "LÄS", textRef: "las3" },
        { id: 21, text: "21. Precis som vanligt te är örtte en så kallad _____ , vilket innebär att man låter blad eller andra växtdelar dra i varmt vatten för att få ut smakämnena.", options: ["A inkarnation", "B infusion", "C induktion", "D inversion"], correctAnswer: "B", category: "MEK" },
        { id: 22, text: "22. Första gången landsnamnet Sverige förekommer i _____ , stavat Swerighe, är i en _____ från Kalmar, daterad 1384.", options: ["A original – bikt", "B klartext – kopia", "C skrift – urkund", "D citat – post"], correctAnswer: "C", category: "MEK" },
        { id: 23, text: "23. Sven Lindqvist bygger ett författarskap där varje ny bok tycks ta vid där den _____ slutade. Så upplever sig läsaren vara inbjuden till en resa, vars _____ tills vidare är oviss men med tiden kommer att framstå som självklar mot bakgrund av hur resan startade. Då uppstår den känsla av _____ som kanske utgör den verkliga nerven i Lindqvists författarskap, när man tar del av det i dess helhet.", options: ["A andra – färdriktning – framtidstro", "B tidigare – utgångspunkt – tvetydighet", "C dessförinnan – grundbetydelse – desperation", "D föregående – slutdestination – kontinuitet"], correctAnswer: "D", category: "MEK" },
        { id: 24, text: "24. Ett klassiskt debattknep i politiken, som dock är ett brott mot vetenskaplig metod, är att ”_____ ”. Med uttrycket menas att man bara refererar utvalda delar av den samlade forskningen, i form av _____ citat som stöder den egna uppfattningen, medan övrigt förbises.", options: ["A låta udda vara jämnt – obetydliga", "B koka soppa på en spik – påhittade", "C blanda äpplen och päron – motsägelsefulla", "D plocka russinen ur kakan – lösryckta"], correctAnswer: "D", category: "MEK" },
        { id: 25, text: "25. Namnförkortningar på företag, organisationer och _____ som uttalas som ord skrivs med versal begynnelsebokstav: Ikea, Jas, Nato, Sida.", options: ["A egenheter", "B koncept", "C dylikt", "D dito"], correctAnswer: "C", category: "MEK" },
        { id: 26, text: "26. I Japan rekryteras ofta ny personal redan när de går i skolan, och de anställda stannar i regel i samma företag till pensionen. I tyst _____ mellan anställda och ledning har företagen _____ sig att behålla sin personal även under kärvare tider.", options: ["A förbindelse – ålagt", "B medgivande – utfäst", "C samförstånd – åtagit", "D uppgörelse – utlyst"], correctAnswer: "C", category: "MEK" },
        { id: 27, text: "27. Det är _____ att många av pidginspråken har liknande grammatiska konstruktioner, trots att deras vokabulärer kan härröra från helt olika språk. Det finns ingen enig uppfattning om orsakerna till dessa likheter.", options: ["A påfallande", "B oberäkneligt", "C underförstått", "D slumpmässigt"], correctAnswer: "A", category: "MEK" },
        { id: 28, text: "28. Den professionella lobbyismens expansion har skapat _____ för en ny typ av politisk _____ med mycket svaga band till vanliga medborgare. När politiskt förtroendekapital förvandlas till en vara på en marknad undergrävs _____ politikerna, partierna och demokratin.", options: ["A en grogrund – elit – tilliten till", "B en hållhake – medelklass – föraktet för", "C ett andrum – agenda – synen på", "D en hävstång – ledning – avståndet till"], correctAnswer: "A", category: "MEK" },
        { id: 29, text: "29. Markförberedelserna inför omplantering inkluderar traditionellt att marken läggs i _____ eller används för andra _____ i flera år.", options: ["A odling – sysslor", "B träda – grödor", "C skifte – åkrar", "D drift – bruk"], correctAnswer: "B", category: "MEK" },
        { id: 30, text: "30. Majoriteten av de nyinsjuknade psykospatienterna förbättras, men vissa får kvarstående restsymtom och sänkt funktionsnivå. För andra får sjukdomen ett episodiskt förlopp med restsymtom mellan _____ .", options: ["A skoven", "B avbrotten", "C ingreppen", "D tillstånden"], correctAnswer: "A", category: "MEK" },
        { id: 31, text: "31. What is argued here about the use of comics for learning science?", options: ["A They can mainly provide simplified versions of scientific explanations.", "B Making them effective requires them to be very well designed.", "C Ultimately it is likely that they will mostly be used as entertainment.", "D They will be especially useful for those already interested in science."], correctAnswer: "B", category: "ELF", textRef: "elf1" },
        { id: 32, text: "32. What is said here?", options: ["A Overconfident people are favored over cleverlooking people in political elections.", "B The human brain is remarkably good at distinguishing people’s inherent characteristics.", "C Most modern political elections are decided entirely by the candidates’ physical appearance.", "D Opinions formed unawares are often more difficult to change than conscious ones."], correctAnswer: "D", category: "ELF", textRef: "elf2" },
        { id: 33, text: "33. What is the basic message in the first two paragraphs?", options: ["A The demand for books has long been in a state of gradual decline.", "B The emotional image of bookstores can now be relegated to the past.", "C The transformation of the book market will be the end of the paper book.", "D The death of the bookstore seems to have been greatly exaggerated."], correctAnswer: "D", category: "ELF", textRef: "elf3" },
        { id: 34, text: "34. What is argued in relation to independent bookstores?", options: ["A Their dominant market share has even taken some experts by surprise.", "B They may well be heading for a brilliant future on a global scale.", "C Their prospects seem to vary a great deal between countries.", "D They are still a long way from realizing their full market potential."], correctAnswer: "C", category: "ELF", textRef: "elf3" },
        { id: 35, text: "35. What is implied in connection with the comeback of indie bookstores?", options: ["A They fill a gap with regard to literature aimed at a more limited readership.", "B The increasing publication of e-books poses a serious threat to their continued existence.", "C Their overall profits are made possible mainly by social media exposure.", "D The massive competition from online booksellers will eventually put them out of business."], correctAnswer: "A", category: "ELF", textRef: "elf3" },
        { id: 36, text: "36. What is said as regards e-books?", options: ["A They were never regarded as a serious threat to paper books.", "B Their takeover of the book market appears virtually unstoppable.", "C They will remain a marginal option to readers of serious literature.", "D Their continuing success story has suffered an unexpected setback."], correctAnswer: "D", category: "ELF", textRef: "elf3" },
        { id: 37, text: "37. What is concluded at the end of the text about indie bookstores?", options: ["A The long-term profitability of their business strategy is beyond doubt.", "B In simplistic terms, they do not seem to be in it just for the money.", "C They may be seen as a temporary feature of the book market.", "D Recently, they have turned into an increasingly lucrative business."], correctAnswer: "B", category: "ELF", textRef: "elf3" },
        { id: 38, text: "38. What is the main argument in this text?", options: ["A Constantly changing recipes may appeal to new groups of consumers.", "B Developing tastes give rise to the acceptance of foreign kinds of dishes.", "C Improved varieties of traditional food are only loosely linked to the original.", "D Modified dishes may give indirect clues about the people who eat them."], correctAnswer: "D", category: "ELF", textRef: "elf4" },
        { id: 39, text: "39. What is implied here about black-browed albatross couples?", options: ["A They separate in a less dramatic fashion than humans do.", "B They seem to have less stable partnerships than most other birds.", "C Their mating patterns have not yet been fully understood.", "D Their partnerships tend to be more temporary than those of humans."], correctAnswer: "A", category: "ELF", textRef: "elf5" },
        { id: 40, text: "40. Which of the following statements best reflects public opinion on crime in 18th century Britain?", options: ["A All kinds of criminal acts require similar punishment.", "B Lack of money is the root cause of most crimes.", "C Criminals’ behaviour is unlikely to change for the better.", "D Crimes involving moral aspects are worse than other crimes."], correctAnswer: "C", category: "ELF", textRef: "elf6" }
    ]
};
