const provpass4 = {
    id: 4,
    title: "Provpass 4 (Verbal)",
    totalTimeInMinutes: 55,
    texts: {
        "vilse": {
            title: "Vilse",
            author: "Niklas Rådström",
            content: `
                <p>En av årets sista nätter sände döden en försändelse av mumlande mörker genom vår vän Gunnars blodomlopp. Ett polletterat kolli som felklarerats vid någon gränsstation för att till sist hamna på en lagerhylla bland oönskade reseffekter i det innersta av hjärtats rum.</p>
                <p>Gunnar dog i sömnen den natten. Dagarna därpå såg vi honom gång på gång: i kön vid snabbköpets kassa, på mellandagspromenad med en okänd hund, på skridskor över insjöns just tillfrusna istäcke ... Till och med in i nyårsdagens eftermiddagslångfilm på tv hade han tagit sig: en silhuett i motljuset vid en öppen verandadörr med hjältinnan vid sin sida.</p>
                <p>Vi arbetar för att hålla oss kvar vid varandra, trots att tiden och dess nitiska budbärare och handgångna män oavbrutet söker hindra oss. De stryker ut reflexerna i fönstrens glas, imfigurerna i badrummens speglar, avtrycken efter försvunna kroppsdelar i sängkläder, soffkuddar och klädesplagg. De vill återställa världen till den plats av rationalitet där människors liv alltid utgör oönskat okända faktorer som hela tiden hotar att göra streck i räkningen och störa de himmelska ekvationernas kalla ordning. De är utsända från en ockupationsmakts propagandaministerium med uppgift att – trots att brev anländer öppnade, tummade och lästa, trots att tidningar censureras till att endast innehålla triviala rubriker, trots att truppförflyttningar och fångtransporter passerar nere på gatan hela nätterna – intala oss att allt är som det ska och att allt vad döden mumlar genom nätterna inte gäller oss.</p>
                <div class="text-footer">
                    <p><em>polletterat kolli = bagage inlämnat för transport till resans slutpunkt</em></p>
                    <p><em>reseffekter = bagage</em></p>
                </div>
            `
        },
        "omvardnad": {
            title: "Omvårdnadsforskning",
            author: "Jonas Nilsson",
            content: `
                <p>Att lösa medicinska gåtor är förstås en viktig forskningsuppgift, men allt fler inser att det är minst lika angeläget att forskningen inriktar sig direkt på att utveckla vården och omsorgen. Samtidigt som sökandet pågår efter exempelvis det som i framtiden botar eller förebygger demens, måste vi säkerställa att vården av dagens sjukdomsdrabbade bedrivs med högsta kvalitet. Till skillnad från för 25–30 år sedan är omvårdnadsforskning i dag ett etablerat forskningsområde, där forskarna bemöts med samma respekt som en alzheimerforskare. En av krafterna bakom denna utveckling är den internationellt kände Per-Olof Sandman, professor vid Umeå universitet, tillika gästprofessor vid Karolinska Institutet med inriktning omvårdnad av demenssjuka.</p>
                <p>– Vi har visat att den forskning som vi bedriver har betydelse och är till nytta för vårt samhälle, säger han.</p>
                <p>Särskilt betydelsefulla för att utveckla kunskapen inom demensvården i Sverige är de nationella riktlinjer som infördes 2010 efter flera års arbete av Per-Olof Sandman och ytterligare ett trettiotal forskare inom olika områden. Arbetet startade med utgångspunkt i forskares och verksamhetsföreträdares bedömning av inom vilka områden det fanns kunskap att sammanställa och var det fanns störst behov att normera vården. Det resulterade i kunskapsbaserade riktlinjer för att tillgodose grundläggande behov inom områden som exempelvis vård i livets slutskede, mat och ätande, fall, munhälsa, urininkontinens och förstoppning, men riktlinjerna lyfter också fram sådant som vårdklimat och betydelsen av personkontinuitet, en anpassad fysisk miljö, välutbildad personal och stöd till närstående.</p>
                <p>Kunskapen finns alltså och de samhälleliga förutsättningarna i övrigt är förhållandevis goda. Men Per-Olof Sandman menar att vården trots detta ofta är uppgifts- och inte personcentrerad, med låga bemanningstal i relation till de förväntningar som finns på personalen. Ibland är det för lite fokus på att ge de boende en meningsfull vardag. Det finns också en överförskrivning av psykofarmaka och det är vanligt med undernäring, fysiska begränsningar och fall. Enligt Per-Olof Sandman är forskningens uppgift att förnya, att utveckla och att ta bort det som är felaktigt. Han beskriver omvårdnadsforskningen som ett ständigt pågående pussel, där det ännu kan vara svårt att få en skarp och entydig bild av forskningsläget.</p>
                <p>– Inom mitt fält lägger vi någon liten pusselbit var, och arbetar väldigt tydligt med vissa motiv. Just nu är ett sådant motiv personcentrerad vård. Där håller vi på att lägga bitar – inte bara i Sverige – för att förstå hur man känner igen personcentrerad vård, hur den kan mätas och hur man ska intervenera för att främja de värderingar som bär upp den.</p>
                <p>Enligt Per-Olof Sandman har omvårdnadsforskningen till dags dato främst varit explorativ. Intervjuer och observationer har använts för att kartlägga olika fenomen. Arbetet har varit betydelsefullt, men ska man få pengar till forskning i dag måste man enligt Per-Olof Sandman arbeta med innovation, implementering och intervention.</p>
                <p>– Det vi har kartlagt och förstått måste omsättas i produkter eller idéer som kan användas på ett mer konkret sätt. Annars kommer vi inte att fortsätta få forskningsmedel. Det kan en del uppleva som hotfullt och andra ser det som en möjlighet. Men vi behöver konklusiv kunskap inom en del områden för att kunna säga: så här ska vi göra, men inte så här.</p>
                <p>Centralt i den omvårdande uppgiften är att se personer som subjekt snarare än som objekt. I det så kallade caringperspektivet handlar omvårdnad alltid om en subjekt–subjekt-relation. Enligt Per-Olof Sandman är det något som över tid tydliggjorts och blivit starkare i sin kontur, men inom demensvården har man periodvis haft ett väldigt instrumentellt och objektifierande synsätt.</p>
                <p>– På 1970- och 1980-talet organiserades omvårdnadsarbetet enligt industrins modell, det löpande bandet. Det kunde man göra eftersom man såg patienten som ett objekt. Men börjar man se kärnan i omvårdnaden som en subjekt–subjekt-relation så blir ju en sådan organisationsmodell omöjlig, säger han.</p>
                <p>Att omvårdnadens organisation byggde på idén om det löpande bandet gjorde att det inte var viktigt med personliga relationer, allt handlade om uppgifter som skulle utföras. Det betydde att alla vårdare var utbytbara, vilket både patienter och vårdare reagerade mot. De krävde en vård som var mer personlig, säger Per-Olof Sandman.</p>
                <p>På 2000-talet har ekonomiska faktorer men även fackliga krav på schemaläggningen lett till förändrade organisationsformer. Utvecklingen har därmed i viss mån stagnerat och till och med gått bakåt. Per-Olof Sandman berättar att han för en tid sedan frågade en sjukhusdirektör: Hur organiseras omvårdnadsarbetet?</p>
                <p>– Då sa han: Det var en bra fråga.</p>
                <p>Men Per-Olof Sandman framhåller att i jämförelse med 1970- och 1980-talet, då man inte ansågs behöva utbildning för att vårda den som var demenssjuk, är vården i dag mycket mer kunskapsbaserad. Personalomsättningen är inte heller lika hög som tidigare. En viktig forskningsuppgift för framtiden blir att titta på bemanningens betydelse för kvalitet, men också på ledarskapets betydelse.</p>
                <p>– Vi vet vad vi ska göra, vi vet hur vi ska göra det, vi vill göra det, men vi behöver starka ledare som går före och visar, som upprätthåller idén om den goda vården, säger Per-Olof Sandman, som tycker att ledarskapet är helt centralt att lyfta fram. Han efterfrågar kompetenta ledare som kan leda genom sitt eget agerande. Det är något som enligt honom har försvunnit i och med att sjuksköterskor och arbetsterapeuter på många boenden har tagits bort.</p>
                <p>– De professionella ledarna som kan komma med integrerad ny kunskap och som utifrån sin kompetens är goda förebilder saknas ofta.</p>
                <p>Ledarskapet ställs också på sin spets i relation till personaltätheten i omvårdnaden.</p>
                <p>– Det finns en risk att vi i framtiden har en väldigt välutbildad vårdpersonal som i teorin vet hur demensvård borde fungera men som inte har förutsättningar att genomföra det.</p>
            `
        },
        "afrika": {
            title: "En afrikansk vår?",
            author: "Erika Bjerström",
            content: `
                <p>Kommer vi att få se en afrikansk vår motsvarande den arabiska? Inte mycket tyder på det, även om det finns en gemensam nämnare för de arabiska länderna i norra Afrika och länderna söder om Sahara. I flera länder finns en stor och rastlös ungdomsgeneration som anser att äldre, diktatoriska män står i vägen för dem. Tack vare globaliseringen är dessa unga uppkopplade mot sociala medier och de inser vilka materiella möjligheter de går miste om. Lägg därtill att de nationellt växande inkomsterna inte fördelas rättvist bland invånarna. Om det någonsin kommer att uppstå en afrikansk vår så kommer den att drivas av en längtan efter välfärd.</p>
                <p>Men mycket skiljer nord från syd, och den viktigaste skillnaden är att länder som Egypten och Tunisien är långt mer homogena samhällen än vad majoriteten av de afrikanska länderna är. Till exempel rymmer Nigeria 170 språkgrupper och i landet finns ännu så länge ingen större samlad rörelse som förmår utmana makten.</p>
                <p>Vid ett gatustånd i Zambias huvudstad Lusaka sitter Loveness Malinga och säljer svamp. Hon gör det för att kunna köpa skoluniformer till sina barn och för att försörja sin familj. Men bara några kvarter bort shoppar medelklassen i nybyggda shoppinggallerior. Ett och samma land rymmer helt skilda verkligheter: medan lantbrukaren lever som på 1800-talet i lerhyddor utan el, kör huvudstadens medelklass runt i dyra bilar. Nya siffror visar att 60 procent av den zambiska befolkningen lever i fattigdom, det är ungefär samma andel som 1996.</p>
                <p>Jag träffar statsvetaren Saviour Mwanbwa som i Lusaka driver tankesmedjan Center for Trade and Development. Han varnar för vad som kan hända i framtiden.</p>
                <p>– De enorma inkomstskillnaderna leder till stora spänningar, det finns ett växande missnöje när det plötsligt verkar som om vissa människor har råd att unna sig vad de vill, medan andra stannar kvar i total fattigdom, säger han.</p>
                <p>Den unge statsvetaren tillhör en växande afrikansk rörelse som kritiserar de utländska företag som deltar i tillväxtboomen men inte betalar skatt på sina vinster – pengar som skulle kunna bidra till landets utveckling. Han påpekar att Afrika förlorar mer i skatteflykt än vad kontinenten erhåller i bistånd. Och både fattiga och rika invånare lägger en stor del av skulden på de egna regeringarna, som inte tycks vara intresserade av att sprida välståndet.</p>
                <p>Vissa hotbilder och larm från den afrikanska kontinenten har varit överrepresenterade i media. Samtidigt finns det andra hotbilder som inte uppmärksammas i tillräckligt stor omfattning. Arbetslöshet, kapital- och skatteflykt, klimatförändringar och islamisering är utan tvivel brännande aktuella frågor, och hur de hoten hanteras av afrikanska ledare och av världssamfundet är avgörande, men vad som ska hända i framtiden är till stor del också kopplat till ungdomsgenerationerna. I en undersökning som Världsbanken lät göra 2011 uppgav 40 procent av dem som gått med i rebellrörelser att det som drev dem var arbetslösheten och känslan av att inte ha någon uppgift i livet. Arbetslösheten bland unga blir på så sätt en tickande bomb; idag är 200 miljoner afrikaner mellan 15 och 24 år. Afrikas befolkning kommer enligt FN att fördubblas till år 2050, och då kommer var femte person på jordklotet att vara afrikan. Vad sker då med de unga som har låg eller ingen utbildning alls men hyser allt större förväntningar på materiell välfärd? Vad kommer att utmärka dem? Även om ungdomarna har låg utbildning talar de kanske flera språk. Är de flexibla och beredda att flytta? Frågorna är många.</p>
                <p>Ungdomar utgör idag 60 procent av de arbetslösa. Kvinnor drabbas hårdare än män, för även om kvinnor har jämförbara kunskaper och erfarenheter så har de svårare att få anställning. Både OECD och African Development Bank har identifierat uppgiften att skapa jobb åt Afrikas alla unga som en av de största utmaningarna framöver. En rapport från Brooking-institutet i Washington visar att 70 procent av alla unga i Kongo-Kinshasa, Kongo-Brazzaville, Etiopien, Malawi, Ghana, Mali, Rwanda, Senegal och Uganda antingen är egenföretagare eller jobbar inom familjens jordbruk eller affärsrörelse. Det gör att unga personer enligt statistiken är fattigare än den genomsnittliga afrikanen. Den sudanesiske miljonären Mo Ibrahims stiftelse har i sin stora studie ”Young Africans and the Employment Challenge” förslag på hur man ska möta de växande kullarna med lågutbildade afrikanska ungdomar. Förslagen är entydiga: fattigdomens utvägar går inte nödvändigtvis via städernas arbetsmarknad, utan via jordbruket.</p>
                <p>Men att arbeta inom jordbruket är inte särskilt eftertraktat eftersom det är så förknippat med generationers slit. Därför anser Mo Ibrahim Foundation att det krävs upplysningskampanjer om vilka slags nya arbetstillfällen som kommer att erbjudas inom det moderna, industrialiserade afrikanska jordbruket: transport, förpackning, förvaring, växtförädling – det finns många nya jobb.</p>
                <p>Samtidigt drabbas varje afrikanskt land nu på olika sätt av klimatförändringarna, och de allra fattigaste drabbas värst eftersom de varken har marginaler att hantera det alltmer oförutsägbara vädret eller kunskap om vad som egentligen sker, utan tiger och lider och sår, om och om igen.</p>
                <p>Jag tänker ofta på John och Ruth som jag träffade i Kenya. De var ett par med en prydligt skött liten gård, de drev ett litet jordbruk, hade tre barn och två oxar. Men deras spannmålsförråd stod helt tomt och de levde i den sorts fattigdom som ekar av hopplöshet, med katastrofen ständigt hotande. Skörden hade just slagit fel – igen. Jag frågade John om han visste varför klimatet blir allt torrare. Svaret överraskade mig.</p>
                <p>– Det är mitt fel, svarade han. Jag tvingas hugga ner träd på min shamba för att göra träkol. För en stor säck som jag säljer längs vägen kan jag försörja min familj en vecka. Men jag har förändrat klimatet genom att hugga ner träden.</p>
                <p>Den kenyanska klimatexpert som följt med oss berättade då för honom om klimatförändringarna, om den rika världens koldioxidutsläpp och om växthuseffekten. John lyssnade noga och stod sedan länge tyst i skuggan av ett akaciaträd. Jag frågade vad han tänkte.</p>
                <p>– Jag tänker att det alltid är den fattige som drabbas.</p>
                <p>Han fick en kärleksfull kram av sin hustru Ruth, och jag frågade vad han tänkte om framtiden.</p>
                <p>– Vi ska göra det vi alltid gör. Vi sår, och ber till Gud. När det blir missväxt sår vi igen – och ber till Gud.</p>
                <p>Den dag John och Ruth har råd att köpa konstgödsel och en traktor, när de får tillgång till den senaste forskningen och därmed nya, mer torkresistenta grödor, när de får elektricitet, kan skicka sina barn till skolan, har råd att köpa en lastbil så att de kan sälja sina spannmål i närmaste stad, då finns det nya Afrika för alla.</p>
                <div class="text-footer">
                    <p><em>den arabiska våren = folkliga uppror mot auktoritära regimer i Mellanöstern och norra Afrika 2011</em></p>
                </div>
            `
        },
        "bond": {
            title: "James Bond Forever? Alternatives",
            author: "Rachel Lloyd, The Economist",
            content: `
                <p>When James Bond first appeared in the pages of Casino Royale (1953), Britain was in a postwar slump. Many bombed-out buildings had yet to be reconstructed or cleared away. The economy was recovering, but there had been many years of <strong>[ 31 ]</strong>, and some commodities were still rationed. Hanging in the air was an uneasy sense that Britain was losing its status as a global power.</p>
                <p>Yet Ian Fleming’s novel was a glamorous tale of derring-do, with sex, gadgets and guns. His 007 was an agent of MI6, Her Majesty’s Secret Service, and he was formidable. He could bed and kill whomever he pleased; he brought down foreign crime syndicates, for the most part on his own, though American money often helped. If Fleming was concerned about the fall of empire, his books provided an escapist form of wish fulfilment.</p>
                <p>“Bond embodied the <strong>[ 32 ]</strong> possibility that England might once again be placed at the centre of world affairs during a period when its world-power status was visibly and rapidly declining,” two critics wrote in Bond and Beyond (1987), a cultural history of the hero.</p>
                <p>The 25th film in the series, No Time to Die, continues this make-believe. The plot follows Bond as he is brought out of retirement in Jamaica for one final job: to track down a scientist. But if the premise for this globe-trotting tale of British exceptionalism seems <strong>[ 33 ]</strong>, the making of the film was anything but. Its title was changed several times. The screenplay went through several iterations; five people are credited as writers.</p>
                <p>Yet the clearest evidence of change may be found not in the film’s depiction of Bond, but of women. <strong>[ 34 ]</strong>, many of the female characters have been mere sexual props, often sporting provocative names. In the wake of #MeToo, Phoebe Waller-Bridge, the creator of the TV series “Fleabag”, was tasked with injecting some humour into the script and making its female figures more realistic. <strong>[ 35 ]</strong> abound that, following Bond’s retirement, MI6 has given the 007 codename to a black woman. Britain may once again be yearning to return to a mythical, glorious past – but James Bond, it seems, is coming to terms with the modern world.</p>
            `
        },
        "cats": {
            title: "Killer Cats",
            author: "Ida Emilie Steinmark, The Guardian Weekly",
            content: `
                <p>In the US, the debate about free-roaming cats has been raging for years. Research has shown that cats – mostly feral but also pets – kill billions of birds and mammals every year. And while it’s primarily motivated by perceived risks from coyotes and traffic, 70% of US cat owners now keep their cats inside, up from 35% in the late 1990s.</p>
                <p>UK cat owners feel differently: about 70% let their cats out, a similar percentage to other European countries. Access to the great outdoors is considered good for cats’ wellbeing, a position shared by charities such as Cats Protection, and there are few predators to worry about. The EU has even declared that it believes in the free movement of cats. “It’s a massive societal difference [from the US],” says Robbie McDonald, a wildlife ecologist at the University of Exeter.</p>
                <p>But cats are prolific hunters of wildlife in the UK and Europe, too. A study based on the 2011 pet population estimates that UK cats kill 160 to 270 million animals annually, a quarter of them birds. The real figure is likely to be even higher, boosted by the pandemic pet craze. So is it time to reconsider the British laissez-faire attitude to free-roaming cats?</p>
                <p>It is well established that cats can have serious impacts on wildlife and even cause extinctions. The most famous example is Lyall’s wren, a small flightless bird that once lived on Stephens Island, New Zealand. When Europeans arrived on the island in the late 1800s, they brought their cats – within the year, Lyall’s wren was gone.</p>
                <p>In the UK and Europe, however, cat invasions happened a long time ago. Cats were brought from the Fertile Crescent to south-eastern Europe several thousand years ago, and then introduced to Britain by the Romans. “We’ve had a much longer history of dealing with any impact that they may have had,” says Philip Baker, a mammologist at the University of Reading.</p>
                <p>Though the relationship between how many cats live in an area and how many birds they take is not straightforward, there is evidence that when cat numbers go up, so do cat kills. A large 2019 study found that the number of garden birds killed by cats in France and Belgium has increased by more than 50% in 15 years, alongside an increase in those countries’ pet cat populations.</p>
                <p>However, not everyone is convinced that cats are actually putting bird populations under pressure. According to Philip Baker, the birds most hunted by cats have so many young that they can afford to lose a lot of them. The UK’s biggest bird charity, the Royal Society for the Protection of Birds, is not particularly concerned about the impact of cats on the British mainland. Instead, it focuses on what it says is driving UK bird declines: global warming, intensive agriculture and expanding towns and cities leading to habitat and food loss. A big reason why it is less worried is the evidence that cats primarily take “the doomed surplus”: weak or injured birds likely to die anyway.</p>
                <p>Although Philip Baker sees no evidence that cats are responsible for UK bird declines, he agrees that there is a problem worth discussing. “Cats are one of the biggest welfare issues for wildlife in this country,” he says.</p>
                <p>So should the British adopt the American way and ditch free roaming? Though it is early days, a growing minority are keeping their cats fully indoors. And that worries Daniel Cummings from Cats Protection. “We’re not saying that all cats need to go outside,” he says, but if indoor-only became the norm, some cats “would have significantly reduced welfare”.</p>
                <p>Instead, Cats Protection recommends a dusk-tilldawn cat curfew. Cats and birds are most active at dusk and dawn. “It’s a sensible compromise,” says Cummings. “You’re effectively reducing the risk of [the cats] getting in a road traffic collision overnight, and also reducing the risk of predation.”</p>
                <p>Tara Pirie, a cat ecologist from the University of Reading who has studied wild leopards in South Africa, is also conflicted about confining cats permanently. She thinks cat-free buffer zones around conservation areas could be a good idea, but that the most important thing is to listen to people’s concerns. “Most people who own cats are animal people,” she says. “They don’t want to have this impact on wildlife either.”</p>
                <p>But from the perspective of Peter Marra, an ecologist at Georgetown University in the US and one of the authors of the 2016 book Cat Wars, none of this goes far enough. “I don’t think there should be a compromise,” he says. “It’s about people taking responsibility for their animal.” What that means, however, might prove to be a cultural difference.</p>
            `
        }
    },
    questions: [
        // ORD
        { id: 1, category: 'ORD', text: 'kontentan', options: ['A: slutfasen', 'B: höjdpunkten', 'C: första intrycket', 'D: motsvarigheten', 'E: huvudinnehållet'], correctAnswer: 'E' },
        { id: 2, category: 'ORD', text: 'diffus', options: ['A: underlig', 'B: avskild', 'C: oklar', 'D: tudelad', 'E: skiftande'], correctAnswer: 'C' },
        { id: 3, category: 'ORD', text: 'upprätthålla', options: ['A: ge styrka åt', 'B: ta upp någons tid', 'C: ligga till grund för', 'D: bevara på en viss nivå', 'E: visa upp en snygg fasad'], correctAnswer: 'D' },
        { id: 4, category: 'ORD', text: 'välvillig', options: ['A: fast besluten', 'B: pålitlig', 'C: optimistisk', 'D: följsam', 'E: sympatiskt inställd'], correctAnswer: 'E' },
        { id: 5, category: 'ORD', text: 'unikum', options: ['A: något som är evigt', 'B: något som är ensamt i sitt slag', 'C: något som är dyrbart', 'D: något som är i ständig förändring', 'E: något som är väl känt'], correctAnswer: 'B' },
        { id: 6, category: 'ORD', text: 'för egen maskin', options: ['A: med kraft', 'B: frivilligt', 'C: utan hjälp', 'D: själviskt', 'E: på rutin'], correctAnswer: 'C' },
        { id: 7, category: 'ORD', text: 'utsikter', options: ['A: möjligheter', 'B: upplevelser', 'C: önskemål', 'D: föreställningar', 'E: synpunkter'], correctAnswer: 'A' },
        { id: 8, category: 'ORD', text: 'kröna', options: ['A: besegra', 'B: omforma', 'C: inhägna', 'D: fullända', 'E: överskrida'], correctAnswer: 'D' },
        { id: 9, category: 'ORD', text: 'banal', options: ['A: nördig', 'B: typisk', 'C: alldaglig', 'D: obildad', 'E: klumpig'], correctAnswer: 'C' },
        { id: 10, category: 'ORD', text: 'hjärtefråga', options: ['A: känslig fråga', 'B: angelägen fråga', 'C: evig fråga', 'D: närgången fråga', 'E: spontan fråga'], correctAnswer: 'B' },
        
        // LÄS - Vilse
        { id: 11, category: 'LÄS', textRef: 'vilse', text: 'Vilken roll spelar tidens "nitiska budbärare och handgångna män" i våra liv, enligt texten?', options: ['A: De påminner oss ständigt om döden och de döda.', 'B: De kommer och hämtar oss när det är dags att dö.', 'C: De vill få oss att glömma döden och de döda.', 'D: De försöker lura oss att döden är ett lyckligt slut.'], correctAnswer: 'C' },
        { id: 12, category: 'LÄS', textRef: 'vilse', text: 'Vilket svarsförslag beskriver två poler som tycks stå mot varandra i texten?', options: ['A: Människors känslor för varandra – tidens kalla rationalitet.', 'B: Vardagens små glädjeämnen – sorgen efter de döda.', 'C: Ungdomlig hoppfullhet – insikten om döden.', 'D: Människans överlevnadsinstinkt – det hårda samhällsklimatet.'], correctAnswer: 'A' },
        
        // LÄS - Omvårdnadsforskning
        { id: 13, category: 'LÄS', textRef: 'omvardnad', text: 'Vad framstår som syftet med de nationella riktlinjer som nämns i texten?', options: ['A: Att förbättra utbildningen av ny vårdpersonal.', 'B: Att säkerställa kvaliteten i den dagliga vården.', 'C: Att underlätta utvärderingen av vården.', 'D: Att stärka den pågående omvårdnadsforskningen.'], correctAnswer: 'B' },
        { id: 14, category: 'LÄS', textRef: 'omvardnad', text: 'Av texten att döma befinner sig omvårdnadsforskningen i en sorts övergångsfas. Hur kan den fasen bäst beskrivas?', options: ['A: Från experiment till teori.', 'B: Från exempel till kartläggning.', 'C: Från beskrivning till analys.', 'D: Från utforskning till tillämpning.'], correctAnswer: 'D' },
        { id: 15, category: 'LÄS', textRef: 'omvardnad', text: 'Vad utmärkte 1970- och 1980-talets "industriella" omvårdnad, enligt texten?', options: ['A: Att den personliga relationen mellan vårdare och patient skulle utvecklas enligt ett givet mönster.', 'B: Att patientens personliga behov inte ansågs viktigare än vårdarens.', 'C: Att vårdarens arbete med patienten begränsades till att sköta bestämda uppgifter.', 'D: Att vårdarens uppgift var att övervaka snarare än att ta hand om patienten.'], correctAnswer: 'C' },
        { id: 16, category: 'LÄS', textRef: 'omvardnad', text: 'Vad är det som gör ledarskapet inom omvårdnad extra viktigt i dag, enligt Per-Olof Sandman?', options: ['A: En ökad personalomsättning.', 'B: Den rådande bemanningssituationen.', 'C: Övergången till uppgiftsfokuserad vård.', 'D: Förväntningar från vårdtagarnas sida.'], correctAnswer: 'B' },

        // LÄS - En afrikansk vår?
        { id: 17, category: 'LÄS', textRef: 'afrika', text: 'Vad talar emot en afrikansk vår, enligt texten?', options: ['A: Etniskt splittrade samhällen.', 'B: En växande ungdomsarbetslöshet.', 'C: Stora ekonomiska skillnader.', 'D: Korrupta makthavare.'], correctAnswer: 'A' },
        { id: 18, category: 'LÄS', textRef: 'afrika', text: 'Vad lyfts i texten fram som ett viktigt led i fattigdomsbekämpningen i Afrika söder om Sahara?', options: ['A: Att förändra afrikanska ungdomars syn på jordbruket.', 'B: Att nyansera den mediala bilden av Afrikas problem.', 'C: Att minska de stora inkomstskillnaderna.', 'D: Att påverka samhället i demokratisk riktning.'], correctAnswer: 'A' },
        { id: 19, category: 'LÄS', textRef: 'afrika', text: 'Vilket påstående överensstämmer bäst med textens resonemang om det förändrade klimatet?', options: ['A: Fattiga människors brist på kunskap och resurser bidrar till klimatförändringarna.', 'B: Afrika är den kontinent som drabbas hårdast av klimatförändringarna.', 'C: Klimatförändringarna kan bromsas med ett moderniserat jordbruk.', 'D: De som är minst skyldiga till klimatförändringarna drabbas hårdast av dem.'], correctAnswer: 'D' },
        { id: 20, category: 'LÄS', textRef: 'afrika', text: 'Vilken av följande frågor kretsar texten som helhet kring?', options: ['A: Vem bär ansvaret för Afrikas problem?', 'B: Vem ska leda det nya Afrika?', 'C: Vad avgör Afrikas framtid?', 'D: Vad kan ena Afrikas befolkningar?'], correctAnswer: 'C' },

        // MEK
        { id: 21, category: 'MEK', text: 'De ekorrar som vi har i Sverige lever inte i flock utan är i det närmaste _____ , det vill säga ensamlevande.', options: ['A: solitära', 'B: separata', 'C: isolerade', 'D: individuella'], correctAnswer: 'A' },
        { id: 22, category: 'MEK', text: 'En betydelsefull _____ av svälten, fattigdomen och eländet i Sverige på 1860-talet var den mycket _____ emigrationen till framför allt Nordamerika.', options: ['A: biverkan – övergripande', 'B: konsekvens – omfattande', 'C: slutsats – förekommande', 'D: insikt – utmanande'], correctAnswer: 'B' },
        { id: 23, category: 'MEK', text: 'Reklamen för en av de mest använda dejtingapparna lyder: "Swipe life!" Den är _____ , för den _____ heta drömmar på något så _____ som ett svep med fingret. Livet, en kraft man bara stundtals känner sig nära, är bara ett svep bort.', options: ['A: beklaglig – inspirerar – snitsigt', 'B: missvisande – baserar – sansat', 'C: förförisk – projicerar – simpelt', 'D: tänkvärd – attraherar – självklart'], correctAnswer: 'C' },
        { id: 24, category: 'MEK', text: 'Ökande bostadspriser _____ i allmänhet de rikaste, eftersom fastighetstillgångar och vinsten från försäljning av dessa är _____ till de övre skikten av inkomstfördelningen.', options: ['A: gynnar – koncentrerade', 'B: drabbar – fördelade', 'C: främjar – privilegierade', 'D: hämmar – begränsade'], correctAnswer: 'A' },
        { id: 25, category: 'MEK', text: 'En vanlig förklaring till morgontrötthet är att vissa personers inre klocka har en _____ som är längre än 24 timmar och därför tenderar att förskjuta dygnsrytmen.', options: ['A: kapacitet', 'B: cirkulation', 'C: periodicitet', 'D: disposition'], correctAnswer: 'C' },
        { id: 26, category: 'MEK', text: 'Under flytten är det viktigt för fåglar att hela tiden ha med sig rätt mängd flygbränsle i form av fett. För mycket fett _____ färden och ökar risken att bli uppäten av rovfåglar. För lite kan leda till svältdöden om födan är _____ .', options: ['A: dröjer – klen', 'B: sackar – vag', 'C: dämpar – låg', 'D: sinkar – knapp'], correctAnswer: 'D' },
        { id: 27, category: 'MEK', text: 'Även om komedins ursprung är _____ anser de flesta forskare i dag att den föddes ur karnevalsliknande fester i samband med Dionysosfestivalerna på 400-talet f.Kr.', options: ['A: omstritt', 'B: omvittnat', 'C: outgrundligt', 'D: otvivelaktigt'], correctAnswer: 'A' },
        { id: 28, category: 'MEK', text: 'Brott mot ordningslagen kan straffas med böter eller fängelse i högst sex månader. Den som _____ eller _____ bryter mot förbud mot förtäring eller förvaring av alkoholdrycker döms till penningböter, om inte gärningen är _____ med straff i någon annan författning.', options: ['A: uppsåtligen – av oaktsamhet – belagd', 'B: tillfälligt – upprepat – relaterad', 'C: direkt – indirekt – försedd', 'D: uttryckligen – underförstått – förenlig'], correctAnswer: 'A' },
        { id: 29, category: 'MEK', text: 'Jag kunde inte se på henne när jag pratade om detta, men jag visste att hon satt och tittade intensivt på mig för att liksom _____ om det var allvar, om jag verkligen menade och stod för vad jag sa.', options: ['A: uppdaga', 'B: betrakta', 'C: utröna', 'D: intyga'], correctAnswer: 'C' },
        { id: 30, category: 'MEK', text: 'För att mildra krisen ville facket och arbetsgivarorganisationen tillsammans genomföra ett omfattande kompetensutvecklingsprogram för de anställda. Men satsningen _____ när regeringen i sin vårbudget inte _____ mer pengar till den fond som skulle finansiera projektet.', options: ['A: föll till föga – värvade', 'B: stötte på patrull – anslog', 'C: gick omlott – äskade', 'D: fick vind i seglen – tillsatte'], correctAnswer: 'B' },

        // ELF - Bond
        { id: 31, category: 'ELF', textRef: 'bond', text: 'Which word best fits gap 31?', options: ['A: austerity', 'B: durability', 'C: prosperity', 'D: liability'], correctAnswer: 'A' },
        { id: 32, category: 'ELF', textRef: 'bond', text: 'Which word best fits gap 32?', options: ['A: strong', 'B: realistic', 'C: imaginary', 'D: complex'], correctAnswer: 'C' },
        { id: 33, category: 'ELF', textRef: 'bond', text: 'Which word best fits gap 33?', options: ['A: backward', 'B: adventurous', 'C: sophisticated', 'D: straightforward'], correctAnswer: 'D' },
        { id: 34, category: 'ELF', textRef: 'bond', text: 'Which word best fits gap 34?', options: ['A: Reluctantly', 'B: Historically', 'C: Occasionally', 'D: Consequently'], correctAnswer: 'B' },
        { id: 35, category: 'ELF', textRef: 'bond', text: 'Which word best fits gap 35?', options: ['A: Sayings', 'B: Arguments', 'C: Rumours', 'D: Incidents'], correctAnswer: 'C' },

        // ELF - Killer cats
        { id: 36, category: 'ELF', textRef: 'cats', text: 'What can be concluded from the first two paragraphs?', options: ['A: Cats in Europe seem overprotected compared to cats in the US.', 'B: The negative impact of cats has so far received limited attention in Britain.', 'C: European cat owners have deliberately ignored the risks to other animals.', 'D: Americans tend to exaggerate the figures relating to the harm done by cats.'], correctAnswer: 'B' },
        { id: 37, category: 'ELF', textRef: 'cats', text: 'What is said about cats in the UK and Europe?', options: ['A: They apparently cause less harm to other animals than American cats.', 'B: Their hunting behaviour has been modified by their long history as pets.', 'C: They are no less dangerous to other animals than are American cats.', 'D: Their owners have managed to domesticate them in different ways.'], correctAnswer: 'C' },
        { id: 38, category: 'ELF', textRef: 'cats', text: 'What can be concluded about cats in relation to the decline of birds in Britain?', options: ['A: In recent years, cats have been universally blamed.', 'B: Cat owners often fail to live up to their responsibility.', 'C: Overall, cats can hardly be assigned a significant role.', 'D: Cats\' harmful effects on bird habitats are beyond doubt.'], correctAnswer: 'C' },
        { id: 39, category: 'ELF', textRef: 'cats', text: 'What are we told about the debate on cats in Britain?', options: ['A: The current trend seems to be heading towards less freedom for cats to spend time outdoors.', 'B: On the whole, there appears to be little interest in the basic issues involved.', 'C: Most cat-owners are worried about the problem of free-roaming cats.', 'D: In general, cat lovers are dead against restricting their pets\' movement in and out of the house.'], correctAnswer: 'A' },
        { id: 40, category: 'ELF', textRef: 'cats', text: 'How can the closing remarks on cats in Britain and America best be summarised?', options: ['A: There is profound disagreement on the environmental harm done by cats.', 'B: British people at large appear more ignorant of cats\' impact than Americans.', 'C: There is a broad consensus as regards cats\' need to be allowed outdoors.', 'D: Clear differences are to be found between British and American attitudes.'], correctAnswer: 'D' }
    ]
};
